<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="104919" started-at="2021-01-18T19:35:49 IST" finished-at="2021-01-18T19:37:34 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="104919" started-at="2021-01-18T19:35:49 IST" finished-at="2021-01-18T19:37:34 IST">
      <class name="testcases.LogInTest">
        <test-method status="PASS" signature="start()[pri:0, instance:testcases.LogInTest@3bd82cf5]" name="start" is-config="true" duration-ms="14" started-at="2021-01-18T19:35:49 IST" finished-at="2021-01-18T19:35:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="startDriver()[pri:0, instance:testcases.LogInTest@3bd82cf5]" name="startDriver" is-config="true" duration-ms="12239" started-at="2021-01-18T19:36:57 IST" finished-at="2021-01-18T19:37:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method status="FAIL" signature="veriWithInValidCredentials(java.util.Map)[pri:0, instance:testcases.LogInTest@3bd82cf5]" name="veriWithInValidCredentials" duration-ms="6838" started-at="2021-01-18T19:37:10 IST" data-provider="getUserThruExcel" finished-at="2021-01-18T19:37:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Coforge@2021@, username=77378}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at reports.ExtentLogger.pass(ExtentLogger.java:21)
at pages.SelemiumAction.click(SelemiumAction.java:35)
at pages.LoginPage.enterCredentials(LoginPage.java:46)
at testcases.LogInTest.veriWithInValidCredentials(LogInTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veriWithInValidCredentials -->
        <test-method status="PASS" signature="Close()[pri:0, instance:testcases.LogInTest@3bd82cf5]" name="Close" is-config="true" duration-ms="4493" started-at="2021-01-18T19:37:17 IST" finished-at="2021-01-18T19:37:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method status="PASS" signature="startDriver()[pri:0, instance:testcases.LogInTest@3bd82cf5]" name="startDriver" is-config="true" duration-ms="7909" started-at="2021-01-18T19:37:21 IST" finished-at="2021-01-18T19:37:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method status="FAIL" signature="veriWithInValidCredentials(java.util.Map)[pri:0, instance:testcases.LogInTest@3bd82cf5]" name="veriWithInValidCredentials" duration-ms="2444" started-at="2021-01-18T19:37:29 IST" data-provider="getUserThruExcel" finished-at="2021-01-18T19:37:31 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Coforge@2021@, username=1234}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at reports.ExtentLogger.pass(ExtentLogger.java:21)
at pages.SelemiumAction.click(SelemiumAction.java:35)
at pages.LoginPage.enterCredentials(LoginPage.java:46)
at testcases.LogInTest.veriWithInValidCredentials(LogInTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veriWithInValidCredentials -->
        <test-method status="PASS" signature="Close()[pri:0, instance:testcases.LogInTest@3bd82cf5]" name="Close" is-config="true" duration-ms="2326" started-at="2021-01-18T19:37:31 IST" finished-at="2021-01-18T19:37:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method status="PASS" signature="CloseD()[pri:0, instance:testcases.LogInTest@3bd82cf5]" name="CloseD" is-config="true" duration-ms="4" started-at="2021-01-18T19:37:34 IST" finished-at="2021-01-18T19:37:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseD -->
      </class> <!-- testcases.LogInTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
