<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-08T10:47:24 IST" name="Suite" finished-at="2021-01-08T10:47:36 IST" duration-ms="11872">
    <groups>
    </groups>
    <test started-at="2021-01-08T10:47:24 IST" name="Test" finished-at="2021-01-08T10:47:36 IST" duration-ms="11872">
      <class name="testcases.LogInTest">
        <test-method is-config="true" signature="Start()[pri:0, instance:testcases.LogInTest@3e6ef8ad]" started-at="2021-01-08T10:47:24 IST" name="Start" finished-at="2021-01-08T10:47:30 IST" duration-ms="6018" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method signature="verifyAttendanceWithInvalidCredentials()[pri:0, instance:testcases.LogInTest@3e6ef8ad]" started-at="2021-01-08T10:47:30 IST" name="verifyAttendanceWithInvalidCredentials" finished-at="2021-01-08T10:47:35 IST" duration-ms="4715" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at testcases.LogInTest.verifyAttendanceWithInvalidCredentials(LogInTest.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAttendanceWithInvalidCredentials -->
        <test-method is-config="true" signature="Close()[pri:0, instance:testcases.LogInTest@3e6ef8ad]" started-at="2021-01-08T10:47:35 IST" name="Close" finished-at="2021-01-08T10:47:36 IST" duration-ms="643" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- testcases.LogInTest -->
      <class name="testcases.LogInTest2">
        <test-method is-config="true" signature="Start()[pri:0, instance:testcases.LogInTest2@346d61be]" started-at="2021-01-08T10:47:24 IST" name="Start" finished-at="2021-01-08T10:47:29 IST" duration-ms="4481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method signature="verifyAttendanceWithValidCredentials()[pri:0, instance:testcases.LogInTest2@346d61be]" started-at="2021-01-08T10:47:29 IST" name="verifyAttendanceWithValidCredentials" finished-at="2021-01-08T10:47:34 IST" duration-ms="5760" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAttendanceWithValidCredentials -->
        <test-method is-config="true" signature="Close()[pri:0, instance:testcases.LogInTest2@346d61be]" started-at="2021-01-08T10:47:34 IST" name="Close" finished-at="2021-01-08T10:47:35 IST" duration-ms="614" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- testcases.LogInTest2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
